name: 🐞 Bug Report
description: File a new bug report
title: '[Bug] <title>'
labels: [Bug]
body:
  - type: markdown
    attributes:
      value: ':stop_sign: Please [search :mag: existing issues](https://github.com/PranavSK/appcraft-astro/issues) to avoid creating duplicates.'
  - type: textarea
    attributes:
      label: Current Behavior
      description: Describe the problem you are experiencing.  **Please do not paste your logs here.**  Screenshots are welcome.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: Describe what you expect to happen instead.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Minimal Reproducible Example
      description: |
        Please provide a the **smallest, complete code snippet** that maintainers can run to reproduce the issue ([read more about what this entails](https://stackoverflow.com/help/minimal-reproducible-example)).  Failing this, any sort of reproduction steps are better than nothing!

        If the result is a large block of text *or* requires multiple files, please:

        - Put it in a [Gist](https://gist.github.com) and paste the link, *or*
        - Provide a link to a new or existing public repository exhibiting the issue
    validations:
      required: true
  - type: textarea
    attributes:
      label: Further Information
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        *Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.*
    validations:
      required: false
